<html>

<style type="text/css">
td{
	text-align: center;

}
</style>

	<table border="1" align="center" width=200 height=200 padding-top=200>

			<tr>
			<td>
				carlos
			</td>
			<td>
				carlos
			</td>
			<td>
				Como
			</td>
			</tr>

		<tr colspan="2">
			<td width=50 height=50 align="center">
				Bien
			</td>
			<td width=100 height=100 align="center">
				y
			</td>
			<td>
				Tu?
			</td>
		</tr>
		<tr>
			<td>
				Fino
			</td>
			<td>
				Voy camino
			</td>
			<td>
				casa
			</td>
		</tr>
	</table>
</html>

